language: java
sudo: false

jdk:
- oraclejdk8

env:
  global:
  - secure: FtuglILQr80dxkbkTcqXV8ibL0oytErM+6IxL3efqicgd6buZgNTpjU/Vld0H1owRqwXXPwXUiI9spWyTUlqtISTI32bGVN3lppHpkgzn7Tw66efYazG8gxlHQFhcVLkJ9ykPFelFbwxyrAQOz0Hwreqk4yvXMee0u7KimkMkjk8ff6BfDGvkAJ8tZO4I+XNH2BO1Jh9oZlcnvQUKbdDIjvHPBJdoe8BKU1vp3LKHzOIzEoHqWos968PNQdCwn1vzJtuOiQkkDOvVe361RRtosQ2U+IhSvQ+uC9mKuCoT/DD8LjuL30sBwDwqMQAjobcLvTriXROihBv1NWFYZvUwAeijo7tXtSLXe3qbWlGFRuzbnothlPeJwcnyfPGitJGT5eRxmkYVWvkTI3QO5gh9TPWF6QJ4BVuzox9ZuN1ZVr4WRpRINza2fOqi487t4Sy3fVednnoTBUyQUSTjCzyMqZb+dq7/DF6SUKt8WnAUM0wm4XhQTAioTOc705SM29wXQsJMvulyhDcThaQlzsbIYKaPm1h+OgJhKopj2shE0AKKi8GTE0ojdWBdzyU00xJYW8C0d7O++lri8CQ6YIgedOMV3SDAwzh48+Nj71tPxNAN5YY9Jl1cCOXz7y78FrkkKeljvSd5zXy8Nb/SVhtJBO8cwBVAQk9MIoJi8MkR0I=
  - secure: iKozdy6XPRV7C2wgMnErz1BRHJJGB9xOLYf7JOEOjDq7RuJT9WDudBHlFTx6pXBQoediByYYTc9E/RmiYBi02aRKA1OaEysoa+Bkoqljb7BiJ6Yo3UmwzpUnwKl7JtnKuXNfJ4dp/VjyCXPhbpDHvaktitDoh+ZQOGvIOVoe59WQmEjchGphddj0W5lA3rXFwfGvFmhKXFvKwBJMKfld8OPy3v1Wbg7hPXTlI4ZkMyQtkiCiUKOHrMmDsR7d5wWg8rzZ3Tx5klld1ukr0LfTHFvPT3U+oDX+13m+HiFbYb2acic5xTITCtBXR+ZOhU6B5LsPcH12ZrKvYwCPBlworeWtTBbloBXylWjhToMliACqVoofcsucAF4296z9MY1mDhHYFSwOhd/HMmmne3Rh+1cKjVtYgRMxxPUzechv+pBZBDsVni0vPjV8T4eY24BaIrat5mV7WN9f4e2it97yhHAR5C8PoOBzOBBeYpQ/WAEaG3V0kpcvZxaIMHOuvrtHybdlrBrUsoircrpzy8ZTumbXfJQR+w3RaN7yMC3iF590zLlWJ+zrp+mWU43Y1hmR6WTECnKJK7WjJm5lPa9aFWTvX24WHBRFBfoUhShz6lk3q15dsnH7EZp/v7GeyJ3IgEma7QsiBsX3cFRqIi3Zufvq/7i5MDp+cXmTeXXZfow=

addons:
  sauce_connect:
    no_ssl_bump_domains: all

install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

script:
- mvn -Dtest_suite_xml=testng.xml test
